services:
  - type: web
    name: facturacion-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_EXPIRE_MINUTES
        value: "480"
      - key: CORS_ORIGINS
        value: "https://facturacion-frontend-nb9w.onrender.com,http://localhost:5173,http://localhost:3000"
      - key: EMPRESA_RAZON_SOCIAL
        value: "Mi Empresa S.A.C."
      - key: EMPRESA_RUC
        value: "20123456789"
      - key: EMPRESA_DIRECCION
        value: "Lima, Peru"
      - key: IGV_PORCENTAJE
        value: "18"
      - key: MISTRAL_API_KEY
        sync: false

  - type: web
    name: facturacion-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: VITE_STREAMLIT_URL
        value: https://facturacion-ml.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: facturacion-ml
    runtime: python
    plan: free
    buildCommand: pip install --no-cache-dir mistralai==1.2.4 && pip install --no-cache-dir -r requirements.txt
    startCommand: streamlit run streamlit_app.py --server.port=$PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: MISTRAL_API_KEY
        sync: false
